version: "3"
services:
  dev:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-12
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
volumes:
  node_modules: